version: '3.5'

services:

### Workspace Utilities ##################################
  workspace:
    image: becagis/becadock_workspace:8.1
    build:
      context: ./workspace
      args:
        - SHELL_OH_MY_ZSH_SYNTAX_HIGHLIGHTING=${SHELL_OH_MY_ZSH_SYNTAX_HIGHLIGHTING}
        - DOCKER_VERSION=${WORKSPACE_DOCKER_VERSION}
        - INSTALL_DOCKER_COMPOSE=${WORKSPACE_INSTALL_DOCKER_COMPOSE}
        - DOCKER_COMPOSE_VERSION=${WORKSPACE_DOCKER_COMPOSE_VERSION}

### PHP-FPM ##############################################
  php-fpm:
    image: becagis/becadock_nginx:8.1
    build:
      context: ./php-fpm
      args:
        - DOCKER_VERSION=${PHP_FPM_DOCKER_VERSION}
        - DOCKER_COMPOSE_VERSION=${PHP_FPM_DOCKER_COMPOSE_VERSION}

### Portainer ################################################
  portainer:
    image: becagis/becadock_portainer

